# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# https://gdevops.gitlab.io/tuto_git/tools/pre-commit/repos_hooks/repos_hooks.html

repos:
# general file checks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# python
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--diff, --check-only]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.272
    hooks:
    -   id: ruff
    # args: [--fix] # Optional: Automatically fix issues where possible
# shell
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    -   id: shellcheck
        args: [-x]
# ### Custom hooks ###
-   repo: local
    hooks:
    -   id: vulture
        name: vulture
        entry: vulture
        language: system
        types: [python]
    # shell
    -   id: check-x
        name: Check X
        entry: ./bin/check-x.sh
        language: script
        files: \.x$
